###
//stock quote
GET https://cloud.iexapis.com/stable/stock/ba/quote?token=

###
//stock logo
GET https://cloud.iexapis.com/stable/stock/ba/logo?token=

###
//stock news
GET https://cloud.iexapis.com/stable/stock/ba/news?token=

###
//stock chart
GET https://cloud.iexapis.com/stable/stock/ba/chart?token=
